name: Erlang CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Erlang/OTP
        uses: erlef/setup-beam@v1
        with:
          otp-version: 25 # Change to your desired version
          rebar3-version: 3.18.0

      - name: Install dependencies
        run: |
          rebar3 update
          rebar3 deps

      - name: Compile project
        run: rebar3 compile

      - name: Run EUnit tests
        run: rebar3 eunit
